- name: Configure Apache Web Server
  hosts: all
  become: true
  vars:
    apache_port: 8080

  tasks:
    - name: Install Apache web server
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Replace the listen port from 80 to 8080
      ansible.builtin.replace:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80$'
        replace: 'Listen {{ apache_port }}'

    - name: Ensure Apache is running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

        
    ## to do configure the apache to listen in port 8080
    ## and restart the apache
    ## use repalce module to replace the port

    

